name: import_js_library
description: Import & use javascript libraries in your flutter web projects
version: 0.0.1
author: Florent Champigny <champigny.florent@gmail.com>
homepage: https://github.com/florent37/import_js_plugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.14.0+3
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ImportJsLibrary
        fileName: import_js_library.dart
