name: inject_js_example_flutter
description: A Flutter project to explain the inject_js package.
publish_to: 'none' 
version: 1.1.0+2

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  inject_js:
    path: ..
    
flutter:
  uses-material-design: true
  assets:
    - assets/hello_world.js